// <auto-generated />
namespace EventWarez.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class atfu : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(atfu));
        
        string IMigrationMetadata.Id
        {
            get { return "202106111748135_atfu"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
